from enum import IntEnum


class Perm:
    CREATE_INSTANT_INVITE = 0
    KICK_MEMBERS = 2**1
    BAN_MEMBERS = 2**2
    ADMINISTRATOR = 2**3
    MANAGE_CHANNELS = 2**4
    MANAGE_GUILD = 2**5
    ADD_REACTIONS = 2**6
    VIEW_AUDIT_LOG = 2**7
    PRIORITY_SPEAKER = 2**8
    STREAM = 2**9
    VIEW_CHANNEL = 2**10
    SEND_MESSAGES = 2**11
    SEND_TTS_MESSAGES = 2**12
    MANAGE_MESSAGES = 2**13
    EMBED_LINKS = 2**14
    ATTACH_FILES = 2**15
    READ_MESSAGE_HISTORY = 2**16
    MENTION_EVERYONE = 2**17
    USE_EXTERNAL_EMOJIS = 2**18
    VIEW_GUILD_INSIGHTS = 2**19
    CONNECT = 2**20
    SPEAK = 2**21
    MUTE_MEMBERS = 2**22
    DEAFEN_MEMBERS = 2**23
    MOVE_MEMBERS = 2**24
    USE_VAD = 2**25
    CHANGE_NICKNAME = 2**26
    MANAGE_NICKNAMES = 2**27
    MANAGE_ROLES = 2**28
    MANAGE_WEBHOOKS = 2**29
    MANAGE_EMOJIS = 2**30

    def __eq__(self, other):
        return other & self == self
